// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = ['slaveOk', 'slave_ok', 'maxPoolSize', 'poolSize', 'autoReconnect', 'auto_reconnect', 'ssl', 'replicaSet', 'rs_name', 'reconnectWait', 'retries', 'readSecondary', 'read_secondary', 'fsync', 'journal', 'safe', 'nativeParser', 'native_parser', 'connectTimeoutMS', 'socketTimeoutMS', 'w', 'authSource', 'wtimeoutMS', 'readPreference', 'readPreferenceTags'];

}).call(this);
