// Generated by CoffeeScript 1.6.3
/*
  backbone-mongo.js 0.5.0
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-mongo
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
*/


(function() {
  var DocumentAdapter_MongoId, JSONUtils, ObjectID;

  ObjectID = require('mongodb').ObjectID;

  JSONUtils = require('backbone-orm/lib/json_utils');

  module.exports = DocumentAdapter_MongoId = (function() {
    function DocumentAdapter_MongoId() {}

    DocumentAdapter_MongoId.id_attribute = '_id';

    DocumentAdapter_MongoId.findId = function(id) {
      var err;
      try {
        return new ObjectID("" + id);
      } catch (_error) {
        err = _error;
        console.log("BackboneMongo: invalid id: " + err);
        return null;
      }
    };

    DocumentAdapter_MongoId.modelFindQuery = function(model) {
      var err;
      try {
        return {
          _id: new ObjectID("" + model.id)
        };
      } catch (_error) {
        err = _error;
        console.log("BackboneMongo: invalid id: " + err);
        return {
          _id: null
        };
      }
    };

    DocumentAdapter_MongoId.nativeToAttributes = function(doc) {
      if (!doc) {
        return {};
      }
      if (doc._id) {
        doc.id = doc._id.toString();
        delete doc._id;
      }
      return doc;
    };

    DocumentAdapter_MongoId.attributesToNative = function(attributes) {
      if (!attributes) {
        return {};
      }
      if (attributes.id) {
        attributes._id = new ObjectID("" + attributes.id);
        delete attributes.id;
      }
      return attributes;
    };

    return DocumentAdapter_MongoId;

  })();

}).call(this);
