// Generated by CoffeeScript 1.6.3
(function() {
  var DocumentAdapter_NoMongoId, JSONUtils, util;

  util = require('util');

  JSONUtils = require('backbone-orm/lib/json_utils');

  module.exports = DocumentAdapter_NoMongoId = (function() {
    function DocumentAdapter_NoMongoId() {}

    DocumentAdapter_NoMongoId.id_attribute = 'id';

    DocumentAdapter_NoMongoId.findId = function(id) {
      return id;
    };

    DocumentAdapter_NoMongoId.modelFindQuery = function(model) {
      return {
        id: model.id
      };
    };

    DocumentAdapter_NoMongoId.nativeToAttributes = function(doc) {
      if (!doc) {
        return {};
      }
      delete doc._id;
      return doc;
    };

    DocumentAdapter_NoMongoId.attributesToNative = function(attributes) {
      return attributes;
    };

    return DocumentAdapter_NoMongoId;

  })();

}).call(this);
