// Generated by CoffeeScript 1.7.1

/*
  backbone-mongo.js 0.5.9
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-mongo
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {
  var DocumentAdapter_NoMongoId, JSONUtils;

  JSONUtils = require('backbone-orm').JSONUtils;

  module.exports = DocumentAdapter_NoMongoId = (function() {
    function DocumentAdapter_NoMongoId() {}

    DocumentAdapter_NoMongoId.id_attribute = 'id';

    DocumentAdapter_NoMongoId.findId = function(id) {
      return id;
    };

    DocumentAdapter_NoMongoId.modelFindQuery = function(model) {
      return {
        id: model.id
      };
    };

    DocumentAdapter_NoMongoId.nativeToAttributes = function(doc) {
      if (!doc) {
        return {};
      }
      delete doc._id;
      return doc;
    };

    DocumentAdapter_NoMongoId.attributesToNative = function(attributes) {
      return attributes;
    };

    return DocumentAdapter_NoMongoId;

  })();

}).call(this);
