// Generated by CoffeeScript 1.6.3
/*
  backbone-mongo.js 0.0.1
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-mongo
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
*/


(function() {
  module.exports = {
    sync: require('./lib/sync'),
    connection_options: require('./lib/connection').options
  };

}).call(this);
