// Generated by CoffeeScript 1.9.0
(function() {
  var BackboneMongo, BackboneORM, _;

  _ = (BackboneORM = require('backbone-orm'))._;

  BackboneMongo = require('../core');

  BackboneMongo.connection_options = {};

  module.exports = function(options) {
    if (options.connection_options) {
      _.extend(BackboneMongo.connection_options, options.connection_options);
    }
    return BackboneORM.configure(_.omit(options, 'connection_options'));
  };

}).call(this);
