// Generated by CoffeeScript 1.7.1
(function() {
  var BackboneMongo, BackboneORM, configure, superConfigure, _;

  _ = (BackboneORM = require('backbone-orm'))._;

  superConfigure = BackboneORM.configure;

  BackboneMongo = require('../core');

  BackboneMongo.connection_options = {};

  module.exports = configure = function(options) {
    if (options.connection_options) {
      _.extend(BackboneMongo.connection_options, options.connection_options);
    }
    return superConfigure(options);
  };

}).call(this);
